language: node_js
node_js:
  - 'stable'
cache:
  directories:
    - 'node_modules'
env: -CI=true
install:
  - yarn config set registry https://registry.npmmirror.com/
  - yarn install
script:
  - npm run build-storybook
  - npm version patch
deploy:
  - provider: pages
    skip_cleanup: true
    github_token: $GITHUB_TOKEN
    local_dir: storybook-static
    on:
      branch: master
  - provider: npm
    email: '15189120919@163.com'
    api_key: '$NPM_TOKEN'
    skip_cleanup: true
    on:
      branch: master
